# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-11 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pm', '0001_initial'),
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaExecute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_end_date', models.DateField(verbose_name='分析完成日期')),
                ('upload_file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='分析结果报告')),
                ('note', models.TextField(verbose_name='实验结果备注')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('ana_experimenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='分析员')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Contract', verbose_name='合同号')),
            ],
            options={
                'verbose_name': '4分析任务执行',
                'verbose_name_plural': '4分析任务执行',
            },
        ),
        migrations.CreateModel(
            name='ExtExecute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_end_date', models.DateField(verbose_name='提取完成日期')),
                ('upload_file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='抽提结果报告')),
                ('note', models.TextField(verbose_name='实验结果备注')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('extSubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.ExtSubmit', verbose_name='子项目编号(抽提)')),
                ('ext_experimenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='抽提实验员')),
            ],
            options={
                'verbose_name': '1提取任务执行',
                'verbose_name_plural': '1提取任务执行',
            },
        ),
        migrations.CreateModel(
            name='LibExecute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_end_date', models.DateField(verbose_name='建库完成日期')),
                ('upload_file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='建库结果报告')),
                ('note', models.TextField(verbose_name='实验结果备注')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('ext_experimenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建库实验员')),
                ('libSubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.LibSubmit', verbose_name='子项目编号(建库)')),
            ],
            options={
                'verbose_name': '2建库任务执行',
                'verbose_name_plural': '2建库任务执行',
            },
        ),
        migrations.CreateModel(
            name='SampleInfoExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=50, verbose_name='样品编号')),
                ('sample_name', models.CharField(max_length=50, verbose_name='样品名称')),
                ('preservation_medium', models.IntegerField(choices=[(1, '纯水'), (2, 'TE buffer'), (3, '无水乙醇'), (4, 'Trizol其他')], default=1, verbose_name='样品保存介质')),
                ('is_RNase_processing', models.IntegerField(choices=[(1, '是'), (2, '否')], default=1, verbose_name='是否经过RNase处理')),
                ('species', models.CharField(max_length=200, verbose_name='物种')),
                ('sample_type', models.IntegerField(choices=[(1, 'g DNA'), (2, '组织'), (3, '细胞'), (4, '土壤'), (5, '粪便其他未提取（请描述）')], default=1, verbose_name='样品类型')),
                ('sample_used', models.CharField(max_length=200, verbose_name='样品提取用量')),
                ('sample_rest', models.CharField(max_length=200, verbose_name='样品剩余用量')),
                ('density_checked', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='浓度ng/uL(公司检测)')),
                ('volume_checked', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='体积uL(公司检测)')),
                ('D260_280', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='D260/280')),
                ('D260_230', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='D260/230')),
                ('DNA_totel', models.CharField(max_length=200, verbose_name='DNA总量')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('quality_control_conclusion', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=1, verbose_name='质检结论')),
            ],
            options={
                'verbose_name': '抽提详细样品信息',
                'verbose_name_plural': '抽提详细样品信息',
            },
        ),
        migrations.CreateModel(
            name='SampleInfoLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=50, verbose_name='样品编号')),
                ('sample_name', models.CharField(max_length=50, verbose_name='样品名称')),
                ('lib_code', models.CharField(max_length=20, null=True, verbose_name='文库号')),
                ('index', models.CharField(max_length=20, null=True, verbose_name='Index')),
                ('lib_volume', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='体积uL(文库)')),
                ('lib_concentration', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='浓度ng/uL(文库)')),
                ('lib_total', models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='总量ng(文库)')),
                ('lib_result', models.IntegerField(choices=[(1, '合格'), (2, '不合格')], default=1, verbose_name='结论(文库)')),
                ('lib_note', models.TextField(blank=True, null=True, verbose_name='备注(文库)')),
            ],
            options={
                'verbose_name': '文库详细样品信息',
                'verbose_name_plural': '文库详细样品信息',
            },
        ),
        migrations.CreateModel(
            name='SampleInfoSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=50, verbose_name='样品编号')),
                ('sample_name', models.CharField(max_length=50, verbose_name='样品名称')),
                ('lib_code', models.CharField(max_length=20, null=True, verbose_name='文库号')),
                ('index', models.CharField(max_length=20, null=True, verbose_name='Index')),
                ('data_request', models.CharField(blank=True, max_length=200, null=True, verbose_name='数据量要求')),
                ('seq_data', models.CharField(blank=True, max_length=200, null=True, verbose_name='测序数据量')),
                ('seq_result', models.IntegerField(choices=[(1, '合格'), (2, '不合格')], default=1, verbose_name='结论(测序)')),
                ('seq_note', models.TextField(blank=True, null=True, verbose_name='备注(文库)')),
            ],
            options={
                'verbose_name': '测序详细样品信息',
                'verbose_name_plural': '测序详细样品信息',
            },
        ),
        migrations.CreateModel(
            name='SeqExecute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_end_date', models.DateField(verbose_name='测序下机日期')),
                ('upload_file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='测序结果报告上传pooling表')),
                ('note', models.TextField(verbose_name='实验结果备注')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('seqSubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.SeqSubmit', verbose_name='子项目编号(建库)')),
                ('seq_experimenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='测序实验员')),
            ],
            options={
                'verbose_name': '3测序任务执行',
                'verbose_name_plural': '3测序任务执行',
            },
        ),
    ]
