# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-12 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqexecute',
            name='note',
            field=models.TextField(blank=True, verbose_name='实验结果备注'),
        ),
        migrations.AlterField(
            model_name='seqexecute',
            name='seq_end_date',
            field=models.DateField(blank=True, verbose_name='测序下机日期'),
        ),
        migrations.AlterField(
            model_name='seqexecute',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='测序结果报告上传pooling表'),
        ),
    ]
