# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-12 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20181012_1059'),
        ('lims', '0002_auto_20181012_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libexecute',
            name='ext_experimenter',
        ),
        migrations.AddField(
            model_name='libexecute',
            name='lib_experimenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Employee', verbose_name='建库实验员'),
        ),
        migrations.AlterField(
            model_name='extexecute',
            name='ext_experimenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Employee', verbose_name='抽提实验员'),
        ),
        migrations.AlterField(
            model_name='seqexecute',
            name='seqSubmit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.SeqSubmit', verbose_name='子项目编号(测序)'),
        ),
        migrations.AlterField(
            model_name='seqexecute',
            name='seq_experimenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Employee', verbose_name='测序实验员'),
        ),
    ]
