# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-12 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_auto_20181012_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleinfoseq',
            old_name='lib_code',
            new_name='seq_code',
        ),
        migrations.RenameField(
            model_name='sampleinfoseq',
            old_name='index',
            new_name='seq_index',
        ),
        migrations.AlterField(
            model_name='sampleinfoseq',
            name='seq_note',
            field=models.TextField(blank=True, null=True, verbose_name='备注(测序)'),
        ),
    ]
