# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-12 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20181012_1059'),
        ('lims', '0004_auto_20181012_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extexecute',
            name='ext_experimenter',
        ),
        migrations.AddField(
            model_name='extexecute',
            name='ext_experimenter',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.Employee', verbose_name='抽提实验员'),
        ),
        migrations.RemoveField(
            model_name='libexecute',
            name='lib_experimenter',
        ),
        migrations.AddField(
            model_name='libexecute',
            name='lib_experimenter',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.Employee', verbose_name='建库实验员'),
        ),
        migrations.RemoveField(
            model_name='seqexecute',
            name='seq_experimenter',
        ),
        migrations.AddField(
            model_name='seqexecute',
            name='seq_experimenter',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.Employee', verbose_name='测序实验员'),
        ),
    ]
