# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-15 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_auto_20181012_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extexecute',
            name='ext_experimenter',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='抽提实验员'),
        ),
        migrations.AlterField(
            model_name='extexecute',
            name='is_submit',
            field=models.BooleanField(default=False, verbose_name='提交'),
        ),
        migrations.AlterField(
            model_name='extexecute',
            name='upload_file',
            field=models.FileField(upload_to='uploads/ext/%Y/%m/%d/', verbose_name='抽提结果报告'),
        ),
        migrations.AlterField(
            model_name='libexecute',
            name='is_submit',
            field=models.BooleanField(default=False, verbose_name='提交'),
        ),
        migrations.AlterField(
            model_name='libexecute',
            name='lib_experimenter',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='建库实验员'),
        ),
        migrations.AlterField(
            model_name='libexecute',
            name='upload_file',
            field=models.FileField(upload_to='uploads/lib/%Y/%m/%d/', verbose_name='建库结果报告'),
        ),
        migrations.AlterField(
            model_name='seqexecute',
            name='is_submit',
            field=models.BooleanField(default=False, verbose_name='提交'),
        ),
        migrations.AlterField(
            model_name='seqexecute',
            name='seq_experimenter',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='测序实验员'),
        ),
        migrations.AlterField(
            model_name='seqexecute',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='uploads/seq/%Y/%m/%d/', verbose_name='测序结果报告上传pooling表'),
        ),
    ]
