# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-16 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_auto_20181015_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anaexecute',
            name='ana_experimenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='分析员'),
        ),
        migrations.AlterField(
            model_name='extexecute',
            name='ext_experimenter',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='抽提实验员'),
        ),
        migrations.AlterField(
            model_name='libexecute',
            name='lib_experimenter',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='建库实验员'),
        ),
        migrations.AlterField(
            model_name='seqexecute',
            name='seq_experimenter',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='测序实验员'),
        ),
    ]
