# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-27 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinfoform',
            name='partner_email',
            field=models.CharField(default='', max_length=200, verbose_name='合作邮箱'),
        ),
        migrations.AddField(
            model_name='sampleinfoform',
            name='sample_diwenjiezhi',
            field=models.IntegerField(choices=[(0, '干冰'), (1, '冰袋'), (2, '无'), (3, '其他')], default=2, verbose_name='低温保存介质'),
        ),
        migrations.AddField(
            model_name='sampleinfoform',
            name='sample_diwenzhuangtai',
            field=models.IntegerField(choices=[(0, '项目进行中'), (1, '项目已完结')], default=0, verbose_name='低温介质到达时状态'),
        ),
        migrations.AddField(
            model_name='sampleinfoform',
            name='sample_species',
            field=models.CharField(default='', max_length=200, verbose_name='物种'),
        ),
    ]
