# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-27 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20180927_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinfo',
            name='data_request',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='数据量要求'),
        ),
    ]
