# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-27 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_sampleinfo_data_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinfoform',
            name='reciver_address',
            field=models.CharField(default='', max_length=200, verbose_name='收件地址'),
        ),
        migrations.AlterField(
            model_name='sampleinfoform',
            name='sample_diwenzhuangtai',
            field=models.IntegerField(choices=[(0, '不合格'), (1, '合格')], default=0, verbose_name='低温介质到达时状态'),
        ),
        migrations.AlterField(
            model_name='sampleinfoform',
            name='sample_jindu',
            field=models.IntegerField(choices=[(0, '项目待启动'), (1, '项目已完结')], default=0, verbose_name='样品进度'),
        ),
        migrations.AlterField(
            model_name='sampleinfoform',
            name='sample_status',
            field=models.IntegerField(choices=[(0, '干冰'), (1, '冰袋'), (2, '无'), (3, '其他')], default=0, verbose_name='样品状态'),
        ),
    ]
