# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-27 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20180927_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleinfoform',
            name='partner_email',
            field=models.EmailField(default='', max_length=254, verbose_name='合作邮箱'),
        ),
    ]
