# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-28 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20180927_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleinfoform',
            name='arrive_time',
            field=models.DateField(blank=True, null=True, verbose_name='样品接收时间'),
        ),
    ]
