# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-29 06:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20180928_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleinfo',
            name='sampleinfoform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.SampleInfoForm', verbose_name='对应样品概要编号'),
        ),
        migrations.AlterField(
            model_name='sampleinfoform',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='客户', to=settings.AUTH_USER_MODEL, verbose_name='客户姓名'),
        ),
    ]
