# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-29 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20180929_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleinfoform',
            name='file_tester',
        ),
    ]
