# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-29 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_remove_sampleinfoform_file_tester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleinfoform',
            name='partner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客户姓名'),
        ),
    ]
