# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20180929_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('department', models.CharField(max_length=200, verbose_name='姓名')),
            ],
        ),
        migrations.AlterField(
            model_name='sampleinfoform',
            name='saler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='销售联系人', to='teacher.Employee', verbose_name='销售代表'),
        ),
        migrations.AlterField(
            model_name='sampleinfoform',
            name='transform_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='物流联系人', to='teacher.Employee', verbose_name='物流联系人'),
        ),
    ]
