# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-11 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20181009_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinfo',
            name='sample_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='样品编号'),
        ),
    ]
