# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_sampleinfo_sample_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleinfo',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '已核对'), (1, '抽提失败'), (2, '建库失败'), (3, '测序失败')], default=0, verbose_name='样品可用状态'),
        ),
    ]
