# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-12 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_sampleinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=200, verbose_name='部门'),
        ),
    ]
