CREATE TABLE auth_group_permissions
(
    id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    FOREIGN KEY (group_id) REFERENCES auth_group (id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (permission_id) REFERENCES auth_permission (id) DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON auth_group_permissions (group_id, permission_id);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON auth_group_permissions (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON auth_group_permissions (permission_id);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (8, 112);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (8, 108);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (8, 109);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (8, 110);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 106);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 108);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 110);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 112);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 32);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 33);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 34);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 35);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 36);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 37);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 38);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 39);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 40);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 41);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 42);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 43);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 44);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 88);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 25);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 26);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 27);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 28);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 29);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 30);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 31);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 57);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 58);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 59);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 60);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 61);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 62);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 63);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 64);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 65);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 66);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 67);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 68);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 69);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 70);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 71);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 72);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 73);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 74);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 75);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 76);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 77);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 78);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 79);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (1, 80);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 88);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 85);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 86);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 89);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 90);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 92);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 92);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 91);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 16);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 81);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 82);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 84);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (4, 87);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (5, 96);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (5, 93);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (5, 94);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (5, 95);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (7, 96);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (7, 88);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (7, 92);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (3, 96);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (3, 92);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (5, 97);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (5, 98);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (5, 100);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (5, 99);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 112);
INSERT INTO auth_group_permissions (group_id, permission_id) VALUES (2, 108);