# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-11 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0011_sampleinfo_sample_number'),
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_cycle', models.PositiveIntegerField(verbose_name='项目分析周期')),
                ('ana_start_date', models.DateField(blank=True, null=True, verbose_name='分析开始日')),
                ('ana_end_date', models.DateField(blank=True, null=True, verbose_name='分析完成日')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='任务号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('sample', models.ManyToManyField(to='teacher.SampleInfo', verbose_name='样品')),
            ],
            options={
                'verbose_name': '5分析任务下单',
                'verbose_name_plural': '5分析任务下单',
            },
        ),
        migrations.CreateModel(
            name='ExtSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_cycle', models.PositiveIntegerField(verbose_name='项目提取周期')),
                ('ext_date', models.DateField(blank=True, null=True, verbose_name='提取完成日')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='提取任务号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('sample', models.ManyToManyField(to='teacher.SampleInfo', verbose_name='样品')),
            ],
            options={
                'verbose_name': '1提取任务下单',
                'verbose_name_plural': '1提取任务下单',
            },
        ),
        migrations.CreateModel(
            name='LibSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_cycle', models.PositiveIntegerField(verbose_name='项目建库周期')),
                ('lib_date', models.DateField(blank=True, null=True, verbose_name='建库完成日')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='任务号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('sample', models.ManyToManyField(to='teacher.SampleInfo', verbose_name='样品')),
            ],
            options={
                'verbose_name': '3建库任务下单',
                'verbose_name_plural': '3建库任务下单',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=20, verbose_name='客户')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='电话')),
                ('income_notes', models.CharField(blank=True, default='', max_length=20, verbose_name='到款记录')),
                ('sample_customer_phone', models.CharField(blank=True, default='', max_length=11, verbose_name='样品联系人电话')),
                ('company', models.CharField(blank=True, default='', max_length=100, verbose_name='地址')),
                ('sub_number', models.CharField(blank=True, default='', max_length=100, verbose_name='子项目编号')),
                ('sub_project', models.CharField(blank=True, default='', max_length=40, verbose_name='子项目的名称')),
                ('project_start_time', models.DateField(blank=True, default=None, max_length=20, verbose_name='立项时间')),
                ('receive_date', models.DateField(blank=True, default=None, verbose_name='收到样品日期')),
                ('sample_type', models.CharField(blank=True, default='', max_length=50, verbose_name='样本类型')),
                ('sample_count', models.IntegerField(blank=True, default=0, verbose_name='样品数量')),
                ('name', models.TextField(blank=True, max_length=100, verbose_name='项目注解')),
                ('is_ext', models.BooleanField(default=False, verbose_name='需提取')),
                ('is_lib', models.BooleanField(default=False, verbose_name='需建库')),
                ('is_seq', models.BooleanField(default=False, verbose_name='需测序')),
                ('is_ana', models.BooleanField(default=False, verbose_name='需分析')),
                ('project_personnel', models.CharField(blank=True, default='', max_length=40, verbose_name='项目管理人员')),
                ('service_type', models.CharField(blank=True, default='', max_length=50, verbose_name='服务类型')),
                ('data_amount', models.CharField(blank=True, default='', max_length=10, verbose_name='数据要求')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='释放报告日')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='释放结果日')),
                ('data_date', models.DateField(blank=True, null=True, verbose_name='释放数据日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='合同节点')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='确认')),
                ('status', models.IntegerField(choices=[(0, '不能启动'), (1, '正常启动'), (2, '提前启动'), (3, '立项处理'), (4, '待首款'), (5, '提取中'), (6, '建库中'), (7, '测序中'), (8, '分析中'), (9, '待尾款'), (10, '尾款已到'), (11, '完成')], default=1, verbose_name='状态')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Contract', verbose_name='合同号')),
                ('saleman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='销售代表', to='teacher.Employee', verbose_name='销售代表')),
                ('sample_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='样品联系人姓名', to='teacher.Employee', verbose_name='销售代表')),
            ],
            options={
                'verbose_name': '0项目管理',
                'verbose_name_plural': '0项目管理',
            },
        ),
        migrations.CreateModel(
            name='SeqSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_cycle', models.PositiveIntegerField(verbose_name='项目测序周期')),
                ('seq_start_date', models.DateField(blank=True, null=True, verbose_name='测序开始日')),
                ('seq_end_date', models.DateField(blank=True, null=True, verbose_name='测序完成日')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='任务号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='提交时间')),
                ('is_submit', models.BooleanField(verbose_name='提交')),
                ('sample', models.ManyToManyField(to='teacher.SampleInfo', verbose_name='样品')),
            ],
            options={
                'verbose_name': '4测序任务下单',
                'verbose_name_plural': '4测序任务下单',
            },
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('contract', 'name')]),
        ),
    ]
