# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-25 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=20, verbose_name='客户')),
                ('project_phone', models.CharField(blank=True, max_length=30, verbose_name='电话')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='项目注解')),
                ('service_type', models.CharField(max_length=50, verbose_name='服务类型')),
                ('data_amount', models.CharField(max_length=10, verbose_name='数据要求')),
                ('is_ext', models.BooleanField(verbose_name='需提取')),
                ('is_qc', models.BooleanField(verbose_name='需质检')),
                ('is_lib', models.BooleanField(verbose_name='需建库')),
                ('ext_cycle', models.PositiveIntegerField(verbose_name='提取周期')),
                ('ext_task_cycle', models.PositiveIntegerField(verbose_name='提取周期')),
                ('ext_date', models.DateField(blank=True, null=True, verbose_name='提取完成日')),
                ('qc_cycle', models.PositiveIntegerField(verbose_name='质检周期')),
                ('qc_task_cycle', models.PositiveIntegerField(verbose_name='质检周期')),
                ('qc_date', models.DateField(blank=True, null=True, verbose_name='质检完成日')),
                ('lib_cycle', models.PositiveIntegerField(verbose_name='建库周期')),
                ('lib_task_cycle', models.PositiveIntegerField(verbose_name='建库周期')),
                ('lib_date', models.DateField(blank=True, null=True, verbose_name='建库完成日')),
                ('seq_cycle', models.PositiveIntegerField(verbose_name='测序周期')),
                ('seq_start_date', models.DateField(blank=True, null=True, verbose_name='测序开始日')),
                ('seq_end_date', models.DateField(blank=True, null=True, verbose_name='测序完成日')),
                ('ana_cycle', models.PositiveIntegerField(verbose_name='分析周期')),
                ('ana_start_date', models.DateField(blank=True, null=True, verbose_name='分析开始日')),
                ('ana_end_date', models.DateField(blank=True, null=True, verbose_name='分析完成日')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='释放报告日')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='释放结果日')),
                ('data_date', models.DateField(blank=True, null=True, verbose_name='释放数据日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='合同节点')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='确认')),
                ('status', models.IntegerField(choices=[(1, '待首款'), (2, '待处理'), (4, '提取中'), (5, '质检中'), (6, '建库中'), (7, '测序中'), (8, '分析中'), (9, '待尾款'), (3, '尾款已到'), (10, '完成')], default=1, verbose_name='状态')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm.Contract', verbose_name='合同号')),
            ],
            options={
                'verbose_name': '0项目管理',
                'verbose_name_plural': '0项目管理',
            },
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('contract', 'name')]),
        ),
    ]
