# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-12 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='SubProject',
        ),
    ]
