# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20181012_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extsubmit',
            name='ext_cycle',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='项目提取周期'),
        ),
        migrations.AlterField(
            model_name='extsubmit',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='提取任务号'),
        ),
        migrations.AlterField(
            model_name='libsubmit',
            name='lib_cycle',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='项目建库周期'),
        ),
        migrations.AlterField(
            model_name='libsubmit',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='任务号'),
        ),
        migrations.AlterField(
            model_name='seqsubmit',
            name='seq_cycle',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='项目测序周期'),
        ),
        migrations.AlterField(
            model_name='seqsubmit',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='任务号'),
        ),
    ]
